name:  CI flows
on:
  workflow_dispatch:
  push:

env:
  PUSH: ${{ contains(github.ref_name, 'main')}}
jobs:
  dockerbuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: build
        uses: docker/build-push-action@v5
        with: 
          context: .
          file: docker/Dockerfile
          push: ${{ env.PUSH }}
          tags: ${{ vars.DOCKERHUB_USERNAME }}/nomad-image-updater:latest 
